name: Deploy to GCE prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to GCE prod via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_GCE_HOST }}
          username: ${{ secrets.PROD_GCE_USER }}
          key: ${{ secrets.PROD_GCE_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/koinvote
            git fetch origin
            git checkout main
            git pull origin main
            npm ci
            npm run build